name: Update Clone Count Badge

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main

jobs:
  update-clone-count:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Fetch Clone Data
      env:
        G_TOKEN: ${{ secrets.G_TOKEN }}
      run: |
        REPO=SimonNyvall/B-branch
        CLONE_COUNT=$(curl -H "Authorization: token $G_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/SimonNyvall/B-branch/traffic/clones | jq '.clones | map(.count) | add')
        echo "{\"schemaVersion\": 1, \"label\": \"clones\", \"message\": \"$CLONE_COUNT\", \"color\": \"blue\"}" > clone_count.json

    - name: Update Gist
      env:
        GIST_ID: ${{ secrets.GIST_ID }}
        G_TOKEN: ${{ secrets.G_TOKEN }}
      run: |
        GIST_URL="https://api.github.com/gists/$GIST_ID"
        curl -X PATCH -H "Authorization: token $G_TOKEN" \
          -d @- $GIST_URL <<EOF
        {
          "files": {
            "clone_count.json": {
              "content": "$(cat clone_count.json)"
            }
          }
        }
        EOF
