name: Update Clone Count Badge

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  push:
    branches:
      - main

jobs:
  update-clone-count:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Fetch Clone Data
      env:
        G_TOKEN: ${{ secrets.G_TOKEN }}
      run: |
        REPO=SimonNyvall/B-branch
        RESPONSE=$(curl -s -H "Authorization: token $G_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/$REPO/traffic/clones)
        echo "API Response: $RESPONSE"  # Log the API response
        CLONE_COUNT=$(echo "$RESPONSE" | jq '.clones | map(.count) | add // 0')
        echo "Clone Count: $CLONE_COUNT"  # Log the clone count
        echo "$(jq -n --arg message "$CLONE_COUNT" '{"schemaVersion": 1, "label": "clones", "message": $message, "color": "blue"}' | jq .)" > clone_count.json

    - name: Update Gist
      env:
        GIST_ID: ${{ secrets.GIST_ID }}
        G_TOKEN: ${{ secrets.G_TOKEN }}
      run: |
        GIST_URL="https://api.github.com/gists/$GIST_ID"
        PAYLOAD=$(jq -n --argfile content clone_count.json '{"files": {"clone_count.json": {"content": $content}}}')
        curl -X PATCH -H "Authorization: token $G_TOKEN" \
             -H "Content-Type: application/json" \
             -d "$PAYLOAD" \
             $GIST_URL
